### PR TITLE
Updated the description and inlineHelpText for the Private__c field

### PR DESCRIPTION
**Pull request by joy-sfdo**
# Critical Changes

# Changes

- Updated the description and help text on the Contact's Private field.

# Issues Closed

### CODE REVIEW

**Comment by joy-sfdo** [comment]
Hi @smarovich,

Would you please review the "Suggested" text in the W-019833 Work Item as well as the sentence in the Changes section? 

Thanks!
Joy

**Comment by smarovich** [comment]
Hi @joy-sfdo, Sorry for the delay. I don't think we need anything in the Changes section since we're just updating help text to more accurately reflect how the field works. I'm going to remove the release note. Thanks!

**Comment by jjbennett** [comment]
@smarovich do the underlying packages even show up in the release notes?

**Comment by smarovich** [comment]
That is a great question, @jjbennett. I'm not sure. @cpolcyn, do Change listed in underlying packages show up in release notes?

**Comment by cpolcyn** [comment]
Underlying packages get their own release notes e.g. https://github.com/SalesforceFoundation/Contacts_and_Organizations/releases/tag/rel%2F3.7

These are not used in creating release notes for the parent package so if needed it should be explicitly added to the release notes for the parent package. When we announce the release in the Hub, we will say something alongside the release notes about there being new versions of underlying packages, but for the release notes themselves that needs to be done in the parent package/repo. They should be added in the pull request (in the parent repo) that updates the underlying package versions.

**Comment by joy-sfdo** [comment]
Thanks, @jjbennett, @smarovich, and @cpolcyn for clarifying the release notes handling for underlying packages.

**Comment by judisohn** [comment]
@cpolcyn @joy-sfdo I think we had discussed not pushing this out until there was more reason? I'd hate for everyone to have to go through the hassle of an underlying package update just to change a simple help text on a single field.

**Comment by davidhabib** [comment]
judi is correct.  we didn't want this to force an update.  we just wanted to get it done, so that next time we need to rev the package, this fix is already there.

**Pull request merged**
