### PR TITLE
 2019-Dec Translations (Refactored)

### PR DESCRIPTION
**Pull request by force2b**
# Critical Changes

# Changes

- Latest labels and objects were pulled for translation and quality improvement for NPSP.

# Issues Closed

### CODE REVIEW

**Comment by force2b** [comment]
@GloryChoe Would you mind reviewing this PR to make sure that all the translations look accurate? These are the same one you created the other day, but pushed and retrieved using Ant to reformat the metadata.

**Comment by GloryChoe** [comment]
@force2b Looks good. Just one label I saw had missing translations: Nonprofit_Edition_Reports - I assume this is expected?

**Comment by force2b** [comment]
Thanks @GloryChoe. See my comment that I put in PR #90 that shows where the translation for `Nonprofit_Edition_Reports` was deleted. That's why it's not in this PR.

**Comment by force2b** [comment]
@GloryChoe As per the email conversation, it's valid that the translation for `Nonprofit_Edition_Reports` is not included in this.

**Comment by force2b** [comment]
**lurch: attach W-035813

**Comment by force2b** [comment]
**lurch: attach W-035813

**Pull request merged**
