### PR TITLE
Removing deprecated fields.

### PR DESCRIPTION
**Pull request by njjc**

### CODE REVIEW

**Comment by njjc** [comment]
@dospromptman this is ready for review. I did a pull, deploy into mrbelvedere@npe01.dev, deleted the appropriate fields through the UI, then a retrievePackagedToSrc. I'm not sure where some of the translation changes came from, I figured you would grock that best.

**Comment by dospromptman** [comment]
It looks like this has the old translations for some reason.  Which fields were you trying to remove?

**Comment by njjc** [comment]
Strangely, I just got this merge request:
https://github.com/SalesforceFoundation/Contacts_and_Organizations/pull/52/files

I had started from master just earlier this morning though...

**Comment by dospromptman** [comment]
It looks like @davidhabib snuck in the Japanese translations 20 minutes ago and make this branch out of date

**Comment by njjc** [comment]
That's what I was thinking: I'll close this PR and start a new branch from scratch, deploy to dev org, delete fields, and recommit. I'm really starting to lose confidence in our process with all the weird stuff that is ending up in diffs...

**Comment by dospromptman** [comment]
git

**Pull request closed without merging**
