### PR TITLE
Updated Workflow Descriptions

### PR DESCRIPTION
**Pull request by sam-knox**
# Critical Changes

# Changes

We added and updated descriptions for several NPSP Workflow Rules.

# Issues Closed

### CODE REVIEW

**Comment by davisagli** [comment]
@force2b that's exactly the scenario that the `regression_org` flow is for -- it installs the current final release, then upgrades to the latest beta release. (Make sure your cumulusci is up to date since we just fixed a bug in this flow in the latest version of cumulusci.)

**Comment by force2b** [comment]
Thanks @davisagli. Haven't used that flow yet.

**Comment by sam-knox** [comment]
**lurch: attach W-009744

**Comment by Julian88Tex** [comment]
@davisagli When running the regression flow it appears I'm getting an error from the unpackage step when it attempts to update Workflow Rules:

```[Failed]: Update of WorkflowRule Contact.npe01__Contact%2EEmailChanged_Alternate: Error on line 3, col 12: Cannot modify managed object: entity=WorkflowRule, component=01Q1D00000027Ui, field=Description, state=installed: newValue='null', oldValue='If the standard Email field is newly entered or changed AND the Preferred Email picklist is set to Alternate THEN Salesforce will fill in the Alternate Email field with the email address entered in the standard Email field.'

Update of WorkflowRule Contact.npe01__Contact%2EEmailChanged_Personal: Error on line 13, col 12: Cannot modify managed object: entity=WorkflowRule, component=01Q1D00000027Uj, field=Description, state=installed: newValue='null', oldValue='If the standard Email field is newly entered or changed AND the Preferred Email picklist is set to Personal or Home THEN Salesforce will fill in the Personal Email field with the email address entered in the standard Email field.'

Update of WorkflowRule Contact.npe01__Contact%2EEmailChanged_Work: Error on line 23, col 12: Cannot modify managed object: entity=WorkflowRule, component=01Q1D00000027Uk, field=Description, state=installed: newValue='null', oldValue='If the standard Email field is newly entered or changed AND the Preferred Email picklist is set to Work THEN Salesforce will fill in the Work Email field with the email address entered in the standard Email field.'

Update of WorkflowRule Contact.npe01__Contact%2EPhoneChanged_Home: Error on line 33, col 12: Cannot modify managed object: entity=WorkflowRule, component=01Q1D00000027Ul, field=Description, state=installed: newValue='null', oldValue='If the standard Phone field is newly entered or changed AND the Preferred Phone picklist is set to Home THEN Salesforce will fill in the Home Phone field with the phone number entered in the standard Phone field.'

Update of WorkflowRule Contact.npe01__Contact%2EPhoneChanged_Mobile: Error on line 43, col 12: Cannot modify managed object: entity=WorkflowRule, component=01Q1D00000027Um, field=Description, state=installed: newValue='null', oldValue='If the standard Phone field is newly entered or changed AND the Preferred Phone picklist is set to Mobile THEN Salesforce will fill in the Mobile Phone field with the phone number entered in the standard Phone field.'

Update of WorkflowRule Contact.npe01__Contact%2EPhoneChanged_Other: Error on line 53, col 12: Cannot modify managed object: entity=WorkflowRule, component=01Q1D00000027Un, field=Description, state=installed: newValue='null', oldValue='If the standard Phone field is newly entered or changed AND the Preferred Phone picklist is set to Other THEN Salesforce will fill in the Other Phone field with the phone number entered in the standard Phone field.'

Update of WorkflowRule Contact.npe01__Contact%2EPhoneChanged_Work: Error on line 63, col 12: Cannot modify managed object: entity=WorkflowRule, component=01Q1D00000027Uo, field=Description, state=installed: newValue='null', oldValue='If the standard Phone field is newly entered or changed AND the Preferred Phone picklist is set to Work THEN Salesforce will fill in the Work Phone field with the phone number entered in the standard Phone field.'

Update of WorkflowRule Contact.npe01__Email only%3A Paste to Work: Error on line 95, col 12: Cannot modify managed object: entity=WorkflowRule, component=01Q1D00000027Ur, field=Description, state=installed: newValue='If there is a value in Email but no values in any email fields or Preferred Email', oldValue='If there is a value in the standard Email field AND no values in any NPSP email fields or Preferred Email, then Salesforce updates two fields: Work Email is updated with the email address in the standard Email field and Preferred Email is set to Work.'

Update of WorkflowRule Contact.npe01__Phone only%3A Paste to Work: Error on line 129, col 12: Cannot modify managed object: entity=WorkflowRule, component=01Q1D00000027Us, field=Description, state=installed: newValue='A new phone value is added to the Phone field and there is no preferred Phone', oldValue='If there is a value in the standard Phone field AND no values in any NPSP phone fields or Preferred Phone, then Salesforce updates two fields: Work Phone is updated with the phone number in the standard Phone field and Preferred Phone is set to Work.'
2019-08-12 13:23:00: Exception in task deploy_trial_config

**Comment by davisagli** [comment]
@Julian88Tex it looks like you're probably running the regression flow for Cumulus rather than for Contacts_and_Organizations package, right? (I'm concluding that because Contacts_and_Organizations' regression_org flow doesn't include a deploy_trial_config step.)

If the goal is to test upgrading to the beta release of Contacts_and_Organizations from the previous final release, then you'll want to run the regression_org flow from within the Contacts_and_Organizations repository, not from within Cumulus. The latter will install the latest beta of Contacts_and_Organizations, but not upgrade it from a previous version.

@davidmreed it does look like the trial metadata in Cumulus needs to be updated to match these changes though.

**Comment by davidmreed** [comment]
@Julian88Tex @davisagli The Trial metadata is next on my list to correct.

**Comment by Julian88Tex** [comment]
@davisagli @davidmreed Ah I guess I assumed it will upgrade all packages and not just the target repos if I ran from Cumulus. Good to know thanks I'll give that a try!

**Comment by Julian88Tex** [comment]
@sam-knox confirmed these changes after updating a package

**Comment by Julian88Tex** [comment]
@davidmreed is there already a WI for this trial metadata change in regards to an update to workflow rules? I'm guessing this will come up at our next regression.

**Comment by davidmreed** [comment]
@Julian88Tex I don't know the original WI that @sam-knox was working from. I created W-035266 to address the conflict with NPSP trial metadata.

**Comment by sam-knox** [comment]
The original WI is: W-009744

**Comment by sam-knox** [comment]
I tried to lurch attach but I don't think I have perms in this repo.

**Comment by Julian88Tex** [comment]
@davidmreed Thanks yeah meant the conflict WI.

**Pull request merged**
